### PR TITLE
fixed a value URI parsing error for Globecoordinate

### PR DESCRIPTION
**Pull request by rongpenl**

### CODE REVIEW

**Comment by GreatYYX** [comment]
Looks like it doesn't fix the issue when `global` is `None`, https://github.com/usc-isi-i2/etk/blob/fbb3ffe65e2ad1b1d387947a17b06dab004dc368/etk/wikidata/value.py#L180

**Comment by rongpenl** [comment]
Is it a good idea to use default `Q2`?

**Comment by GreatYYX** [comment]
@rongpenl IDK, you need to check with wikidata's spe to see if it's a proper choice. Probably @saggu will fix the `None` issue.

**Comment by rongpenl** [comment]
I think it is safe to assume `Q2` according to the spec [here](https://www.wikidata.org/wiki/Help:Data_type):

> Globe defaults to "Earth" (globe: http://www.wikidata.org/entity/Q2).

**Comment by saggu** [comment]
lets not merge into master

**Pull request closed without merging**
