### PR TITLE
Displacy renders and compares 'en_core_web_sm' to 'en_core_web_lg'

### PR DESCRIPTION
**Pull request by Ljferrer**
Fixed last line with displacy.render(..., jupyter=True) so notebook will display labeled ents in PyCharm. Shows difference in outputs of spaCy's pertained language models when using 'en_core_web_sm' or 'en_core_web_lg'.

### CODE REVIEW

**Comment by Ljferrer** [comment]
^This is more of a quick and dirty patch than a real bug fix. May require attention in the future...

**Comment by GreatYYX** [comment]
please remove all `print` statements (`print` should only be used in examples)

**Comment by Ljferrer** [comment]
Rodger that. 

- Lukas

**Comment by szeke** [comment]
@GreatYYX please review and merge if ready, thx.

**Pull request merged**
