### PR TITLE
path fixed for windows  system

### PR DESCRIPTION
**Pull request by iAmeeth**

### CODE REVIEW

**Comment by saggu** [comment]
Why are there 2 file changes? Did you delete the second file by mistake? @iAmeeth

**Comment by iAmeeth** [comment]
I get this when I switch to the branch.

`$ git checkout etk2
error: unable to create file examples/ranking_pipeline/resources/output/Will North Korea's Supreme Leader Kim Jong-un experience a significant leadership disruption before 1 July 2018?  _result.jl: Invalid argument`

That's why the file is getting deleted.

**Comment by GreatYYX** [comment]
path is`./tmp/etk.log`? why?

**Comment by GreatYYX** [comment]
It's not the correct way to fix. the problem is windows doesn't have `/tmp`, if you change it to `./tmp`, yes problem fixed but it's confusing.

the fix should be, make etk can get temp path on different os correctly, check this: https://docs.python.org/3.6/library/tempfile.html

**Comment by GreatYYX** [comment]
commit https://github.com/usc-isi-i2/etk/commit/b15e69fd4a2432625bbf26ae8773b930fbbe4cad fixed this issue

**Pull request merged**
