### PR TITLE
Development

### PR DESCRIPTION
**Pull request by linqyd**
edit sphinx config file.
modify docstring format

### CODE REVIEW

**Comment by linqyd** [comment]
Hey, please merge this pull request although there are three test cases fail. The test case failures are caused by unreasonable test case design. Please refer this issue #335

**Comment by GreatYYX** [comment]
FYI, if the variable or method needs to be private, it should starts with SINGLE underscore (PEP8). double underscore is used by interpreter for name mangling. also, double heading and trailing underscore is a name convention in python builtin class.

**Comment by saggu** [comment]
@linqyd the latest commit is failing in travis, pls check

**Comment by linqyd** [comment]
Just created an issue. Please refer to #339

**Pull request merged**
