### PR TITLE
expedite glossary extractor

### PR DESCRIPTION
**Pull request by xkgoodbest**
if we set tokenizer as None, extractor will use regex to extract tokens to expedite the extraction

### CODE REVIEW

**Comment by xkgoodbest** [comment]
> Quick question: is the tokenizer usually from spaCy?
> 
> Note: on mobile rn

Yep, usually spacy.

**Comment by Ljferrer** [comment]
Is this problem related to [this issue](https://github.com/explosion/spaCy/issues/1508) at all? i.e. poor speed despite high CPU usage (particularly kernel usage).

**Comment by Ljferrer** [comment]
If so, I might have a hot-fix

**Comment by Ljferrer** [comment]
Sorry it didn’t solve your specific issue. 

Nevertheless, I’m still curious if we were facing the same fundamental problem. Did you happen to see a change in CPU usage on `$ htop`?

My hot-fix wouldn’t boost the speed of a single process, but it would prevent it from wastfully using too many cores. Setting `os.environ[‘OPENBLAS_NUM_THREADS’] = ‘1’` or `os.environ[‘OPENBLAS_NUM_THREADS’] = ‘2’` would then allow you to spawn multiple processes, but reaping the full benefit requires some extra effort (beyond just setting the environment variable). 

This may be hard to guarantee in ETK, but if it is fundamentally related to [this issue](
https://github.com/explosion/spaCy/issues/1508), it would probably be worth trying to come up with a workaround since the problem has been around for almost a year now.

**Pull request merged**
