### PR TITLE
adding support for csv output, and taking pdf input url

### PR DESCRIPTION
**Pull request by majidghgol**
- added support for csv output, and taking pdf input url
- added two new requirements, `requests` and `tabula`.

### CODE REVIEW

**Comment by szeke** [comment]
@majidghgol great, please check the CI errors.

**Comment by majidghgol** [comment]
@szeke @saggu CI breaks in date parser, I can't see how the table extractor code can affect this:

```
FAIL: test_ground_truth (etk.unit_tests.test_date_extractor.TestDateExtractor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/usc-isi-i2/etk/etk/unit_tests/test_date_extractor.py", line 91, in test_ground_truth
    self.assertEqual(e[0].value if e else '', expected)
AssertionError: '2019-08-01' != '2020-08-01'
- 2019-08-01
?   ^^
+ 2020-08-01
?   ^^
```

**Comment by szeke** [comment]
@greatyyx please take a look at the issues with date parser

**Comment by GreatYYX** [comment]
@szeke @majidghgol  I did a fix in development branch which can be merged into this branch later https://github.com/usc-isi-i2/etk/commit/9d9c2473fd1530bcf0e07f95d2b3c9cbbe1ed0e7 .

If you take a look of this code snippet, originally it was trying to this heuristic https://github.com/usc-isi-i2/etk/commit/9d9c2473fd1530bcf0e07f95d2b3c9cbbe1ed0e7#diff-f3440cd16ca15fefa02e2c4c0a440349L483-L487 if `PREFER_DATES_FROM` is `current` (basically find a close year if year is not specified). I don't know if it's intended. But for me, if it's `current`, it should simply use current year.

**Comment by GreatYYX** [comment]
I'm going to merge this PR to development since the failure of CI is caused by date extractor and I just fixed it.

**Pull request merged**
