### PR TITLE
First pass at adding HTI extractors

### PR DESCRIPTION
**Pull request by mattprice09**
I've been working with @szeke on a separate project and he indicated that we should include our extractors here (I work with Human Trafficking Initiative) as there might be some useful code here.

I've included the extractors for: 
- ethnicity
- indicators
- military friendly
- name
- "no blacks allowed"
- phone
- posting ID
- time
- trucker friendly

Please note that for the sake of time, I didn't clean up some of our older code (namely, `parse_ethnicity` and many of the helpers in `parser_helpers.py`. I figured getting a working version merged in would be more worthwhile for everyone interested. Code cleaning and ETK API integration will occur in future PRs.

Additionally, I included many of our other functions that we use in `utils.py` in the case that they are useful to anyone. If they are and they require additional data files, I'm happy to include those in a follow-up PR. For now, the only 2 functions that are used in this demo are:

- `countries()` and `post_id_backpage_groups()`

I will remove any that are not useful, just let me know.

### CODE REVIEW

**Comment by mattprice09** [comment]
On a test set of 1600 ads, we currently have an F1 score of 89% for the name parser and 99% for the phone parser. These are the two that have been manually tested the most (since we use these two in the matching algorithm), so we have smaller N sizes for the other ones.

**Comment by saggu** [comment]
Hi Matt, could you create a pull request for the `development` branch. I will close this pul request

**Comment by mattprice09** [comment]
No problem - do you want me to just push it to `development` directly then make a PR, or branch from `development` and make a PR to push that branch into `development`?

**Comment by saggu** [comment]
When you create a pull request, instead of `master` , you can choose `development`

Like this - https://github.com/usc-isi-i2/etk/compare/development...mattprice09:hti-extractors

**Pull request closed without merging**
